name: Publish to Registry

name: publish-packages

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '0.0.0'
        required: true

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/publish'

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Restore
      run: dotnet restore src/D2DLib.sln

    - name: Pack
      run: msbuild src/D2DLibExport/D2DLibExport.csproj /t:pack -p:Configuration=Release /p:DefineConstants=X64 -p:PackageVersion=1.2.3 -p:OutputPath=.dist -t:restore -p:RestorePackagesConfig=true

    - name: Push
      run: dotnet nuget push src/D2DLibExport/.dist/D2DLibExport.${{github.event.inputs.version}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} -s https://nuget.pkg.github.com/PauloHMattos/index.json --skip-duplicate
        
