name: Publish to Registry

on: 
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/nuget'

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Restore
      run: dotnet restore src/D2DLib.sln

    - name: Build Native Library
      run: msbuild src/d2dlib/D2DLib.vcxproj -p:Configuration=Release -p:Platform="x64"

    - name: Pack Managed Libraries
      run: msbuild src/D2DWinForm/D2DWinForm.csproj /t:pack -p:Configuration=Release -p:Platform="x64" -p:OutputPath=.dist -p:PackageVersion=0.0.0-g${{ github.sha }} -p:RepositoryUrl=${{ matrix.RepositoryUrl }}

    - name: Publish the package to GPR
      run: dotnet nuget push src/D2DWinForm/.dist/D2DLib-x64.0.0.0-g${{ github.sha }}.nupkg
